/* tslint:disable */
/* eslint-disable */
/**
 * Brand API
 * API for retrieving and searching brand data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BrandNaicsGet200ResponseCodesInner
 */
export interface BrandNaicsGet200ResponseCodesInner {
    /**
     * NAICS code
     * @type {string}
     * @memberof BrandNaicsGet200ResponseCodesInner
     */
    'code'?: string;
    /**
     * NAICS title
     * @type {string}
     * @memberof BrandNaicsGet200ResponseCodesInner
     */
    'title'?: string;
}

