/* tslint:disable */
/* eslint-disable */
/**
 * Brand API
 * API for retrieving and searching brand data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BrandRetrieveGet200ResponseBrand } from './brand-retrieve-get200-response-brand';

/**
 * 
 * @export
 * @interface BrandRetrieveGet200Response
 */
export interface BrandRetrieveGet200Response {
    /**
     * Status of the response, e.g., \'ok\'
     * @type {string}
     * @memberof BrandRetrieveGet200Response
     */
    'status'?: string;
    /**
     * 
     * @type {BrandRetrieveGet200ResponseBrand}
     * @memberof BrandRetrieveGet200Response
     */
    'brand'?: BrandRetrieveGet200ResponseBrand;
    /**
     * HTTP status code
     * @type {number}
     * @memberof BrandRetrieveGet200Response
     */
    'code'?: number;
}

