/* tslint:disable */
/* eslint-disable */
/**
 * Brand API
 * API for retrieving and searching brand data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BrandRetrieveGet200ResponseBrandColorsInner
 */
export interface BrandRetrieveGet200ResponseBrandColorsInner {
    /**
     * Color in hexadecimal format
     * @type {string}
     * @memberof BrandRetrieveGet200ResponseBrandColorsInner
     */
    'hex'?: string;
    /**
     * Name of the color
     * @type {string}
     * @memberof BrandRetrieveGet200ResponseBrandColorsInner
     */
    'name'?: string;
}

