/* tslint:disable */
/* eslint-disable */
/**
 * Brand API
 * API for retrieving and searching brand data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BrandSearchGet200ResponseResultsInner } from './brand-search-get200-response-results-inner';

/**
 * 
 * @export
 * @interface BrandSearchGet200Response
 */
export interface BrandSearchGet200Response {
    /**
     * Status of the response
     * @type {string}
     * @memberof BrandSearchGet200Response
     */
    'status'?: string;
    /**
     * Array of search results
     * @type {Array<BrandSearchGet200ResponseResultsInner>}
     * @memberof BrandSearchGet200Response
     */
    'results'?: Array<BrandSearchGet200ResponseResultsInner>;
}

