/* tslint:disable */
/* eslint-disable */
/**
 * Brand API
 * API for retrieving and searching brand data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Stock market information for this brand (will be null if not a publicly traded company)
 * @export
 * @interface BrandRetrieveGet200ResponseBrandStock
 */
export interface BrandRetrieveGet200ResponseBrandStock {
    /**
     * Stock ticker symbol
     * @type {string}
     * @memberof BrandRetrieveGet200ResponseBrandStock
     */
    'ticker'?: string;
    /**
     * Stock exchange name
     * @type {string}
     * @memberof BrandRetrieveGet200ResponseBrandStock
     */
    'exchange'?: string;
}

