/* tslint:disable */
/* eslint-disable */
/**
 * Brand API
 * API for retrieving and searching brand data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BrandRetrieveGet200ResponseBrandSocialsInner
 */
export interface BrandRetrieveGet200ResponseBrandSocialsInner {
    /**
     * Type of social media, e.g., \'facebook\', \'twitter\'
     * @type {string}
     * @memberof BrandRetrieveGet200ResponseBrandSocialsInner
     */
    'type'?: string;
    /**
     * URL of the social media page
     * @type {string}
     * @memberof BrandRetrieveGet200ResponseBrandSocialsInner
     */
    'url'?: string;
}

