/* tslint:disable */
/* eslint-disable */
/**
 * Brand API
 * API for retrieving and searching brand data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BrandSearchGet200ResponseInner
 */
export interface BrandSearchGet200ResponseInner {
    /**
     * URL of the brand\'s logo
     * @type {string}
     * @memberof BrandSearchGet200ResponseInner
     */
    'logo'?: string;
    /**
     * Title or name of the brand
     * @type {string}
     * @memberof BrandSearchGet200ResponseInner
     */
    'title'?: string;
    /**
     * Domain name of the brand
     * @type {string}
     * @memberof BrandSearchGet200ResponseInner
     */
    'domain'?: string;
}

