/* tslint:disable */
/* eslint-disable */
/**
 * Brand API
 * API for retrieving and searching brand data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BrandRetrieveGet200ResponseBrandAddress } from './brand-retrieve-get200-response-brand-address';
// May contain unused imports in some cases
// @ts-ignore
import type { BrandRetrieveGet200ResponseBrandBackdropsInner } from './brand-retrieve-get200-response-brand-backdrops-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { BrandRetrieveGet200ResponseBrandColorsInner } from './brand-retrieve-get200-response-brand-colors-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { BrandRetrieveGet200ResponseBrandFontsInner } from './brand-retrieve-get200-response-brand-fonts-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { BrandRetrieveGet200ResponseBrandLogosInner } from './brand-retrieve-get200-response-brand-logos-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { BrandRetrieveGet200ResponseBrandSocialsInner } from './brand-retrieve-get200-response-brand-socials-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { BrandRetrieveGet200ResponseBrandStock } from './brand-retrieve-get200-response-brand-stock';

/**
 * Detailed brand information
 * @export
 * @interface BrandRetrieveGet200ResponseBrand
 */
export interface BrandRetrieveGet200ResponseBrand {
    /**
     * The domain name of the brand
     * @type {string}
     * @memberof BrandRetrieveGet200ResponseBrand
     */
    'domain'?: string;
    /**
     * The title or name of the brand
     * @type {string}
     * @memberof BrandRetrieveGet200ResponseBrand
     */
    'title'?: string;
    /**
     * A brief description of the brand
     * @type {string}
     * @memberof BrandRetrieveGet200ResponseBrand
     */
    'description'?: string;
    /**
     * The brand\'s slogan
     * @type {string}
     * @memberof BrandRetrieveGet200ResponseBrand
     */
    'slogan'?: string;
    /**
     * An array of brand colors
     * @type {Array<BrandRetrieveGet200ResponseBrandColorsInner>}
     * @memberof BrandRetrieveGet200ResponseBrand
     */
    'colors'?: Array<BrandRetrieveGet200ResponseBrandColorsInner>;
    /**
     * An array of logos associated with the brand
     * @type {Array<BrandRetrieveGet200ResponseBrandLogosInner>}
     * @memberof BrandRetrieveGet200ResponseBrand
     */
    'logos'?: Array<BrandRetrieveGet200ResponseBrandLogosInner>;
    /**
     * An array of backdrop images for the brand
     * @type {Array<BrandRetrieveGet200ResponseBrandBackdropsInner>}
     * @memberof BrandRetrieveGet200ResponseBrand
     */
    'backdrops'?: Array<BrandRetrieveGet200ResponseBrandBackdropsInner>;
    /**
     * An array of social media links for the brand
     * @type {Array<BrandRetrieveGet200ResponseBrandSocialsInner>}
     * @memberof BrandRetrieveGet200ResponseBrand
     */
    'socials'?: Array<BrandRetrieveGet200ResponseBrandSocialsInner>;
    /**
     * 
     * @type {BrandRetrieveGet200ResponseBrandAddress}
     * @memberof BrandRetrieveGet200ResponseBrand
     */
    'address'?: BrandRetrieveGet200ResponseBrandAddress;
    /**
     * Indicates if the brand information is verified
     * @type {boolean}
     * @memberof BrandRetrieveGet200ResponseBrand
     */
    'verified'?: boolean;
    /**
     * 
     * @type {BrandRetrieveGet200ResponseBrandStock}
     * @memberof BrandRetrieveGet200ResponseBrand
     */
    'stock'?: BrandRetrieveGet200ResponseBrandStock;
    /**
     * An array of fonts used by the brand\'s website
     * @type {Array<BrandRetrieveGet200ResponseBrandFontsInner>}
     * @memberof BrandRetrieveGet200ResponseBrand
     */
    'fonts'?: Array<BrandRetrieveGet200ResponseBrandFontsInner>;
}

