/* tslint:disable */
/* eslint-disable */
/**
 * Brand API
 * API for retrieving and searching brand data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BrandRetrieveGet200ResponseBrandFontsInner
 */
export interface BrandRetrieveGet200ResponseBrandFontsInner {
    /**
     * Usage of the font, e.g., \'title\', \'body\', \'button\'
     * @type {string}
     * @memberof BrandRetrieveGet200ResponseBrandFontsInner
     */
    'usage'?: string;
    /**
     * Name of the font
     * @type {string}
     * @memberof BrandRetrieveGet200ResponseBrandFontsInner
     */
    'name'?: string;
}

