/* tslint:disable */
/* eslint-disable */
/**
 * Brand API
 * API for retrieving and searching brand data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Resolution of the logo image
 * @export
 * @interface BrandRetrieveGet200ResponseBrandLogosInnerResolution
 */
export interface BrandRetrieveGet200ResponseBrandLogosInnerResolution {
    /**
     * Width of the image in pixels
     * @type {number}
     * @memberof BrandRetrieveGet200ResponseBrandLogosInnerResolution
     */
    'width'?: number;
    /**
     * Height of the image in pixels
     * @type {number}
     * @memberof BrandRetrieveGet200ResponseBrandLogosInnerResolution
     */
    'height'?: number;
}

