/* tslint:disable */
/* eslint-disable */
/**
 * Brand API
 * API for retrieving and searching brand data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BrandRetrieveGet200ResponseBrandBackdropsInnerResolution } from './brand-retrieve-get200-response-brand-backdrops-inner-resolution';
// May contain unused imports in some cases
// @ts-ignore
import type { BrandRetrieveGet200ResponseBrandColorsInner } from './brand-retrieve-get200-response-brand-colors-inner';

/**
 * 
 * @export
 * @interface BrandRetrieveGet200ResponseBrandBackdropsInner
 */
export interface BrandRetrieveGet200ResponseBrandBackdropsInner {
    /**
     * URL of the backdrop image
     * @type {string}
     * @memberof BrandRetrieveGet200ResponseBrandBackdropsInner
     */
    'url'?: string;
    /**
     * Array of colors in the backdrop image
     * @type {Array<BrandRetrieveGet200ResponseBrandColorsInner>}
     * @memberof BrandRetrieveGet200ResponseBrandBackdropsInner
     */
    'colors'?: Array<BrandRetrieveGet200ResponseBrandColorsInner>;
    /**
     * 
     * @type {BrandRetrieveGet200ResponseBrandBackdropsInnerResolution}
     * @memberof BrandRetrieveGet200ResponseBrandBackdropsInner
     */
    'resolution'?: BrandRetrieveGet200ResponseBrandBackdropsInnerResolution;
}

