/* tslint:disable */
/* eslint-disable */
/**
 * Brand API
 * API for retrieving and searching brand data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BrandRetrieveGet401Response
 */
export interface BrandRetrieveGet401Response {
    /**
     * Error code indicating the type of error
     * @type {string}
     * @memberof BrandRetrieveGet401Response
     */
    'error_code'?: BrandRetrieveGet401ResponseErrorCodeEnum;
}

export const BrandRetrieveGet401ResponseErrorCodeEnum = {
    InternalError: 'INTERNAL_ERROR',
    Valid: 'VALID',
    NotFound: 'NOT_FOUND',
    Forbidden: 'FORBIDDEN',
    UsageExceeded: 'USAGE_EXCEEDED',
    RateLimited: 'RATE_LIMITED',
    Unauthorized: 'UNAUTHORIZED',
    Disabled: 'DISABLED',
    InsufficientPermissions: 'INSUFFICIENT_PERMISSIONS'
} as const;

export type BrandRetrieveGet401ResponseErrorCodeEnum = typeof BrandRetrieveGet401ResponseErrorCodeEnum[keyof typeof BrandRetrieveGet401ResponseErrorCodeEnum];


